# conda environment file
# to create the env, run conda env create -f conda-env.yml

name: cmbcosmo

channels:
    - conda-forge
    - pytorch     # for sbi

dependencies:
    - python=3.9
    - numpy
    - matplotlib
    - emcee
    - tqdm
    - pip
    - pip:
      - chainconsumer
    # for simcmb
    - camb
    - h5py
    - jupyter
    - namaster    # install via conda; pip install is a nightmare
    # for sbi
    - arviz
    - cudatoolkit
    - jupyterlab
    - notebook
    - pillow
    - pip:
      - "pyknos>=0.14.2"
      - "pyro-ppl>=1.3.1"
    - "pytorch >= 1.8.0"
    - scikit-learn
    - scipy
    # now install sbi via pip
    - pip:
      - sbi