# paths to be used
# current_machine should be the machine on which code is
# run and <current_machine>_paths should be present.
# setup_config will setup the outdir based on current_machine.
paths:
    current_machine: 'arc'
    arc_paths:
        outdir: '~/deepskies/cmbcosmo/outdir/'

# details for datavector generation
# also establishes the "truth"
datavector:
    cosmo: {'r': 0.04, 'Alens': 1.0}
    lmin_lmax: [5,300]
    detector_white_noise: True
    fsky: 0.9
    camb_params: {'H0': 67.32117, 'ombh2': 0.0223828,
                  'omch2': 0.1201075, #mnu': 0.06,
                  'omk': 0, #tau': 0.06,
                  'As': 2.100549e-09,
                  'ns':  0.9660499,
                  'halofit_version': 'mead2016'
                  }

# inference details
inference:
    # likelihood params, details
    params_to_fit: ['Alens']
    param_labels: ['$A_{lens}$']
    param_priors: [[0.5, 1.5]]
    # details re mcmc
    mcmc:
        # random seed for the starting points
        randomseed_starts: 4627
        # chain details
        nwalkers: 20
        nsteps: 100
    # details re sbi
    sbi:
        infer_nsims: 1000
        posterior_nsamples: 1000
        sampling_seed: 1425
        # predictive checks (pc) related
        pc_nsamples: 500
        pc_seed: 10
        pc_inds_for_pairplot: [0,1,2,3,4,10,15,20,25]
        # simulation based check (sbc) related
        sbc_nruns: 1000
        sbc_nsamples: 1000
        sbc_seed: 15