# paths to be used
# current_machine should be the machine on which code is
# run and <current_machine>_paths should be present.
# setup_config will setup the outdir based on current_machine.
paths:
    current_machine: 'arc'
    arc_paths:
        outdir: '~/deepskies/cmbcosmo/outdir/'

# details for datavector generation
# also establishes the "truth"
datavector:
    cosmo: {'r': 0.04, 'Alens': 1.0}
    lmin_lmax: [5,300]
    fsky: 0.9
    camb_params: {
        'ini': '/home/hawan/deepskies/cmbcosmo/runscripts/configs/planck_2018.ini',
        'Init.power.At': 1,
        'WantTensor': True,
        'WantTransfer': False
        }


# inference details
inference:
    # likelihood params, details
    params_to_fit: ['r']
    param_labels: ['$r$']
    param_priors: [[0,1]]
    # details re mcmc
    mcmc:
        # random seed for the starting points
        randomseed_starts: 4627
        # chain details
        nwalkers: 20
        max_nsteps: 100
        # burnin criterion
        burnin_tau_factor: 3        # burnin = burnin_tau_factor * tau steps
        # following for convergence checks for early stopping
        check_every_nsteps: 50
        convergence_ntau: 100       # convergence when chain is convergence_ntau * tau
        convergence_deltau: 0.01    # convergence when tau changes by < convergence_deltau
    # details re sbi
    sbi:
        infer_nsims: 1000
        infer_seed: 214
        posterior_nsamples: 1000
        sampling_seed: 1425
        # predictive checks (pc) related
        pc_nsamples: 500
        pc_seed: 10
        pc_inds_for_pairplot: [0,1,2,3,4,10,15,20,25]
        # simulation based check (sbc) related
        sbc_nruns: 1000
        sbc_nsamples: 1000
        sbc_seed: 15