# paths to be used
# current_machine should be the machine on which code is
# run and <current_machine>_paths should be present.
# setup_config will setup the outdir based on current_machine.
paths:
    current_machine: 'arc'
    arc_paths:
        outdir: '~/deepskies/cmbcosmo/outdir/'

# details for datavector generation
# also establishes the "truth"
datavector:
    cosmo: {'r': 0.04, 'Alens': 1.0}
    lmin_lmax: [5,300]
    ell_binning: True
    nells: 20
    fsky: 0.9
    camb_params: {
        'ini': '/home/hawan/deepskies/cmbcosmo/runscripts/configs/planck_2018.ini',
        'Init.power.At': 1,
        'WantTensor': True,
        'WantTransfer': False
        }

# inference details
inference:
    # likelihood params, details
    params_to_fit: ['r', 'Alens']
    param_labels: ['$r$', '$A_{lens}$']
    param_priors: [[0,1], [0.5, 1.5]]
    # details re mcmc
    mcmc:
        # random seed for the starting points
        randomseed_starts: 4627
        # chain details
        nwalkers: 70
        max_nsteps: 1000
        # burnin criterion
        burnin_tau_factor: 3        # burnin = burnin_tau_factor * tau steps
        # following for convergence checks for early stopping
        check_every_nsteps: 50
        convergence_ntau: 50        # convergence when chain is convergence_ntau * tau
        convergence_deltau: 0.01    # convergence when tau changes by < convergence_deltau
    # details re sbi
    sbi:
        # sims related
        infer_nsims: 1000
        infer_seed: 214
        # embedding params; applicable only if embed (user flag) is used
        # not really needed if ell-binning is happening for the spectra (see datavector
        # config above)
        embedding:
            # input_dim will be nells, based on lmin, lmax
            # optimization params: applicable if optimize-embed (user flag) is used
            optimization_params:
                testsize: 0.3   # relative size of test
                ntrials: 100
                outdim_range: [5, 100]
                nlayers_range: [1, 15]
                nhidden_range: [10, 100]
            # embedding hyperparams to be used if the params are not optimized. ad hoc.
            embedding_params:
                outdim: 20
                nlayers: 2
                nhidden: 50
        # sampling related
        posterior_nsamples: 1000
        sampling_seed: 1425
        # predictive checks (pc) related
        pc_nsamples: 500
        pc_seed: 10
        # simulation based check (sbc) related
        sbc_nruns: 500
        sbc_nsamples: 1000
        sbc_seed: 15