# paths to be used
# current_machine should be the machine on which code is
# run and <current_machine>_paths should be present.
# setup_config will setup the outdir based on current_machine.
paths:
    current_machine: 'local'
    local_paths:
        outdir: '~/deepskies/cmbcosmo/outdir/'

# details for datavector generation
# also establishes the "truth"
datavector:
    randomseed: 924
    cosmo: {'r': 0.04}

# inference details
inference:
    # likelihood params, details
    params_to_fit: ['r']
    param_labels: ['$r$']
    param_priors: [[0.001,1]]
    # starting cosmo 
    # using the same seed as data (above) - need to think whether this is the way to go
    cosmo: {'r': 0.03}
    # details re mcmc
    mcmc:
        # random seed for the starting points
        randomseed_starts: 4627
        # chain details
        nwalkers: 20
        nburn: 10
        nchain: 10